### ISSUE TITLE
Data Accessibility and Availability 

### ISSUE THREAD

**Issue by DHGK** [yuGithuuub/Normal_liver_visium#1]
Hi @yuGithuuub ,

Congratulations on this nice publication! As I am very intrigued by your findings and would like to take a closer look at your data, I have some issues to access the spatial images from your publication.

It is mentioned in the data availability section of the manuscript that "All processed data have been uploaded to the figshare database(https://www.nature.com/articles/s41597-022-01676-w#ref-CR26). These data include filtered_feature_bc_matrix.h5, cloupe file and spatial files."  However in the figshare directory for this article, I could not find neither filtered_feature_bc_matrix.h5 or spatial files for this data. I wonder if you could kindly updated your figshare repository. 

Thank you!

**Comment by yuGithuuub** [comment]
Hi DHGK:
  Thank you very much for your reminder that there is a lack of h5 files in our compressed package. 
  Currently, the loupe file can be obtained through a compressed package. The rest of the spatial data can be obtained through the .rdata file.
  The rest of the files I will add to the new link as soon as possible, thanks！

**Comment by DHGK** [comment]
Thank you for your promptly reply, @yuGithuuub !

I could view the loupe file, but I couldn't load the loupe with Seurat or other packages to R. Also currently, only the integrated data folder has a .RData file but the integrated Seurat object doesn't actually contain @image assay slot. L5 or 18 don't have the .RData.

Thank you!

**Comment by yuGithuuub** [comment]
Hi DHGK
I regenerated a link, please check if it meets your needs.（https://figshare.com/s/9540591b32f67a415735 ）

**Comment by DHGK** [comment]
Thank you again for following up! I could see that there are two shared files, but I could not actually download them. When I tried, I got this error message:
```
{"message": "Entity not found: file", "code": "EntityNotFound"}
```

**Comment by yuGithuuub** [comment]
Hi DHGK:
  Sorry for what you've been through.
  Please try again if you can download successfully.
  （https://doi.org/10.6084/m9.figshare.22321447.v1 ）
Best
Sz Yu

**Comment by DHGK** [comment]
Thanks a lot! It works :)
